// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP5D2xpA9HnZLStL30dfUcA0-TMOAAiPM',
    appId: '1:1047984062059:web:38d5a09cdaf79f05303b2e',
    messagingSenderId: '1047984062059',
    projectId: 'fir-flutter-codelab-de2a9',
    authDomain: 'fir-flutter-codelab-de2a9.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-de2a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBITv36iuhOAuNLhUwUl3vxLwzx0JOHYnA',
    appId: '1:1047984062059:android:673a2009d5970c23303b2e',
    messagingSenderId: '1047984062059',
    projectId: 'fir-flutter-codelab-de2a9',
    storageBucket: 'fir-flutter-codelab-de2a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMghzHEiAwth3WE3whFUQcv_bdreHjAb4',
    appId: '1:1047984062059:ios:32e18bdde3ed53ca303b2e',
    messagingSenderId: '1047984062059',
    projectId: 'fir-flutter-codelab-de2a9',
    storageBucket: 'fir-flutter-codelab-de2a9.appspot.com',
    iosClientId: '1047984062059-57g26p1i5bgbfqg17gcsgejqf14bdqrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMghzHEiAwth3WE3whFUQcv_bdreHjAb4',
    appId: '1:1047984062059:ios:32e18bdde3ed53ca303b2e',
    messagingSenderId: '1047984062059',
    projectId: 'fir-flutter-codelab-de2a9',
    storageBucket: 'fir-flutter-codelab-de2a9.appspot.com',
    iosClientId: '1047984062059-57g26p1i5bgbfqg17gcsgejqf14bdqrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
